using System.IO;
using System.Text.Json;

namespace LingoIsland.Video;

/// <summary>一支影片之已存字幕（#174）：逐句 cue（含說話人標註／YAML 編修／AI 推斷結果）＋來源是否自動生成＋存檔時間。以 VideoId 為鍵。</summary>
public sealed class SavedSubtitle
{
    public string VideoId { get; set; } = "";
    public bool IsAutoGenerated { get; set; }
    public List<SubtitleCue> Cues { get; set; } = new();
    public string SavedAt { get; set; } = ""; // ISO 8601
}

/// <summary>
/// 影片字幕本機儲存（[modVideoCapture模組]，#174）：每支影片之字幕存
/// <c>%APPDATA%\LingoIsland\subtitles\{videoId}.json</c>——重開／重選同片即還原、免重抓 yt-dlp、保留說話人與 YAML 編修。
/// 首次抓取後即存；AI 說話人疊加／YAML 套用後覆寫；影片自清單刪除時連同刪其字幕。讀寫失敗降級不致命（回 null／靜默）。
/// </summary>
public sealed class SubtitleStore
{
    private static readonly JsonSerializerOptions Opts = new() { WriteIndented = true };
    private readonly string _dir;

    public SubtitleStore(string? dir = null) { _dir = dir ?? DefaultDir; }

    public static string DefaultDir => Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "LingoIsland", "subtitles");

    private string PathFor(string videoId) => Path.Combine(_dir, Sanitize(videoId) + ".json");

    /// <summary>YouTube 影片 ID 僅含 [A-Za-z0-9_-]；防呆濾除其餘字元，避免以外來字串組出越界路徑。</summary>
    private static string Sanitize(string videoId) =>
        new string((videoId ?? "").Where(c => char.IsLetterOrDigit(c) || c is '_' or '-').ToArray());

    /// <summary>存一支影片之字幕（覆寫）；videoId 空、無有效鍵字元或 cues 空則略過（不建立空檔）。</summary>
    public void Save(string videoId, bool isAutoGenerated, IReadOnlyList<SubtitleCue> cues)
    {
        if (string.IsNullOrWhiteSpace(videoId) || Sanitize(videoId).Length == 0 || cues is null || cues.Count == 0) { return; }
        var data = new SavedSubtitle
        {
            VideoId = videoId,
            IsAutoGenerated = isAutoGenerated,
            Cues = cues.ToList(),
            SavedAt = DateTimeOffset.Now.ToString("o"),
        };
        try
        {
            Directory.CreateDirectory(_dir);
            File.WriteAllText(PathFor(videoId), JsonSerializer.Serialize(data, Opts));
        }
        catch { /* 寫入失敗不影響主流程 */ }
    }

    /// <summary>讀一支影片之已存字幕；無檔／空／解析失敗回 null。</summary>
    public SavedSubtitle? TryLoad(string videoId)
    {
        if (string.IsNullOrWhiteSpace(videoId)) { return null; }
        try
        {
            var path = PathFor(videoId);
            if (!File.Exists(path)) { return null; }
            var data = JsonSerializer.Deserialize<SavedSubtitle>(File.ReadAllText(path));
            return data is { Cues.Count: > 0 } ? data : null;
        }
        catch { return null; }
    }

    /// <summary>刪一支影片之已存字幕（該影片自清單移除時）。</summary>
    public void Remove(string videoId)
    {
        if (string.IsNullOrWhiteSpace(videoId)) { return; }
        try { var p = PathFor(videoId); if (File.Exists(p)) { File.Delete(p); } }
        catch { /* 不致命 */ }
    }

    /// <summary>清空所有已存字幕（Clear all videos 時）。</summary>
    public void Clear()
    {
        try { if (Directory.Exists(_dir)) { Directory.Delete(_dir, recursive: true); } }
        catch { /* 不致命 */ }
    }
}
