using System.Diagnostics;
using System.IO;

namespace LingoIsland.Video;

/// <summary>
/// 以本機 <c>yt-dlp</c> 取 YouTube 影片英文字幕（[techItem字幕擷取]／[modVideoCapture模組] 影片擷取契約，spec#2）：
/// <see cref="Process"/> 啟動、僅下載字幕檔（VTT）、以 <see cref="SubtitleParser"/> 解析為逐句 cue。
/// **兩趟策略**：先只取<b>人工（真人）字幕</b>（乾淨句級、最佳學習素材）；查無才退取<b>自動字幕</b>
/// （逐字滾動、較不精準），並於 <see cref="SubtitleFetchResult.IsAutoGenerated"/> 標記供 UI 提示。
/// 無字幕／yt-dlp 缺失／私人或無效影片／逾時／非零離開碼一律擲 <see cref="SubtitleException"/>（中止該片、不當機）。
/// **僅取字幕文字、不下載影片內容**（<c>--skip-download</c>）。
/// </summary>
public sealed class YtDlpSubtitleFetcher : ISubtitleFetcher
{
    private readonly string _ytDlpPath;
    private readonly int _timeoutSec;

    public YtDlpSubtitleFetcher(string ytDlpPath = "yt-dlp", int timeoutSec = 60)
    {
        _ytDlpPath = ytDlpPath;
        _timeoutSec = timeoutSec;
    }

    public async Task<SubtitleFetchResult> FetchAsync(string videoUrlOrId, CancellationToken ct = default)
    {
        if (string.IsNullOrWhiteSpace(videoUrlOrId))
        {
            throw new SubtitleException("Please paste a YouTube link or video ID.");
        }

        var url = videoUrlOrId.Trim();
        var dir = Path.Combine(Path.GetTempPath(), "lingoisland-subs-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(dir);
        try
        {
            var outTemplate = Path.Combine(dir, "sub");
            // 僅字幕、不下載影片；英文（含變體 en.*）；VTT 格式；單片不展開清單。
            const string common = "--skip-download --sub-langs \"en.*\" --sub-format vtt --no-playlist";

            // 第一趟：僅人工（真人）字幕——乾淨句級，到句暫停體驗最佳。查得即用、標記非自動。
            await RunAsync($"{common} --write-subs -o \"{outTemplate}\" \"{url}\"", ct);
            var manual = PickVtt(dir);
            if (manual is not null)
            {
                var manualCues = SubtitleParser.Parse(await File.ReadAllTextAsync(manual, ct));
                if (manualCues.Count > 0) return new SubtitleFetchResult(manualCues, IsAutoGenerated: false);
            }

            // 第二趟：無人工字幕→退自動字幕（en-orig/auto，逐字滾動、句數暴增）。SubtitleParser 盡力收斂、標記為自動供 UI 提示。
            ClearVtts(dir);
            var (exit, stderr) = await RunAsync($"{common} --write-auto-subs -o \"{outTemplate}\" \"{url}\"", ct);
            var auto = PickVtt(dir);
            if (auto is null)
            {
                if (exit != 0)
                {
                    throw new SubtitleException("Could not fetch subtitles: " + FirstMeaningfulLine(stderr));
                }
                throw new SubtitleException("This video has no English subtitles available.");
            }

            var autoCues = SubtitleParser.Parse(await File.ReadAllTextAsync(auto, ct));
            if (autoCues.Count == 0)
            {
                throw new SubtitleException("Subtitles were found but contained no readable lines.");
            }
            return new SubtitleFetchResult(autoCues, IsAutoGenerated: true);
        }
        finally
        {
            try { Directory.Delete(dir, recursive: true); } catch { /* best-effort temp cleanup */ }
        }
    }

    /// <summary>自暫存夾挑英文 VTT：優先精確 <c>.en.vtt</c>（自動字幕之翻譯版通常較 en-orig 乾淨）、次非 orig、末任一；無則 null。</summary>
    private static string? PickVtt(string dir)
    {
        var vtts = Directory.EnumerateFiles(dir, "*.vtt").ToList();
        return vtts.FirstOrDefault(f => f.EndsWith(".en.vtt", StringComparison.OrdinalIgnoreCase))
            ?? vtts.FirstOrDefault(f => f.IndexOf("orig", StringComparison.OrdinalIgnoreCase) < 0)
            ?? vtts.FirstOrDefault();
    }

    /// <summary>清掉第一趟殘留的 VTT，避免第二趟 PickVtt 誤挑到人工趟的檔。</summary>
    private static void ClearVtts(string dir)
    {
        foreach (var f in Directory.EnumerateFiles(dir, "*.vtt").ToList())
        {
            try { File.Delete(f); } catch { /* best-effort */ }
        }
    }

    private async Task<(int exit, string stderr)> RunAsync(string args, CancellationToken ct)
    {
        var psi = new ProcessStartInfo
        {
            FileName = _ytDlpPath,
            Arguments = args,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true,
        };

        Process? p;
        try
        {
            p = Process.Start(psi);
        }
        catch (Exception ex)
        {
            throw new SubtitleException(
                "yt-dlp could not be started (ensure yt-dlp is installed and on PATH): " + ex.Message);
        }
        if (p is null)
        {
            throw new SubtitleException("yt-dlp could not be started (ensure yt-dlp is installed and on PATH).");
        }

        using (p)
        {
            using var cts = CancellationTokenSource.CreateLinkedTokenSource(ct);
            cts.CancelAfter(TimeSpan.FromSeconds(_timeoutSec));
            var stdoutTask = p.StandardOutput.ReadToEndAsync(cts.Token);
            var stderrTask = p.StandardError.ReadToEndAsync(cts.Token);
            try
            {
                await p.WaitForExitAsync(cts.Token);
            }
            catch (OperationCanceledException) when (!ct.IsCancellationRequested)
            {
                try { p.Kill(entireProcessTree: true); } catch { /* ignore */ }
                throw new SubtitleException($"Fetching subtitles timed out ({_timeoutSec}s).");
            }
            var stderr = await stderrTask;
            _ = await stdoutTask;
            return (p.ExitCode, stderr);
        }
    }

    private static string FirstMeaningfulLine(string s)
    {
        var line = s.Split('\n').FirstOrDefault(l => l.Trim().Length > 0)?.Trim() ?? "unknown error";
        return line.Length > 200 ? line[..200] + "…" : line;
    }
}
