using System.IO;
using LingoIsland.Video;
using Xunit;

namespace LingoIsland.Tests;

/// <summary>影片字幕存檔（<see cref="SubtitleStore"/>，#174）：存→讀往返（含說話人與自動生成旗標）、缺檔回 null、空 cues 不建檔、刪除、清空。</summary>
public class SubtitleStoreTests
{
    private static string TempDir() => Path.Combine(Path.GetTempPath(), "li-subs-" + Guid.NewGuid().ToString("N"));
    private static void TryDelete(string dir) { try { if (Directory.Exists(dir)) { Directory.Delete(dir, true); } } catch { /* 清理盡力 */ } }

    [Fact]
    public void SaveThenLoad_RoundTripsCuesAndFlag()
    {
        var dir = TempDir();
        try
        {
            var store = new SubtitleStore(dir);
            var cues = new List<SubtitleCue> { new("Hello there", 1.0, "Ryder"), new("Bark!", 2.5) };
            store.Save("abc123DEF-_", isAutoGenerated: true, cues);
            var loaded = store.TryLoad("abc123DEF-_");
            Assert.NotNull(loaded);
            Assert.True(loaded!.IsAutoGenerated);
            Assert.Equal(2, loaded.Cues.Count);
            Assert.Equal("Hello there", loaded.Cues[0].Text);
            Assert.Equal(1.0, loaded.Cues[0].StartSec);
            Assert.Equal("Ryder", loaded.Cues[0].Speaker); // 說話人標註隨字幕存回
            Assert.Null(loaded.Cues[1].Speaker);
        }
        finally { TryDelete(dir); }
    }

    [Fact]
    public void TryLoad_Missing_ReturnsNull()
    {
        var dir = TempDir();
        try { Assert.Null(new SubtitleStore(dir).TryLoad("nope")); }
        finally { TryDelete(dir); }
    }

    [Fact]
    public void Save_EmptyCues_NotPersisted()
    {
        var dir = TempDir();
        try
        {
            var store = new SubtitleStore(dir);
            store.Save("vid", false, new List<SubtitleCue>());
            Assert.Null(store.TryLoad("vid"));
        }
        finally { TryDelete(dir); }
    }

    [Fact]
    public void Remove_DeletesSaved()
    {
        var dir = TempDir();
        try
        {
            var store = new SubtitleStore(dir);
            store.Save("vid", false, new List<SubtitleCue> { new("x", 0.0) });
            Assert.NotNull(store.TryLoad("vid"));
            store.Remove("vid");
            Assert.Null(store.TryLoad("vid"));
        }
        finally { TryDelete(dir); }
    }

    [Fact]
    public void Clear_RemovesAll()
    {
        var dir = TempDir();
        try
        {
            var store = new SubtitleStore(dir);
            store.Save("a", false, new List<SubtitleCue> { new("x", 0.0) });
            store.Save("b", false, new List<SubtitleCue> { new("y", 1.0) });
            store.Clear();
            Assert.Null(store.TryLoad("a"));
            Assert.Null(store.TryLoad("b"));
        }
        finally { TryDelete(dir); }
    }
}
